---
abstract: unknown
author:
  - 'Rene Schickbauer <rene.schickbauer@magnapowertrain.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Server-Simple-CGI-PreFork
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Server::Simple: 0.44
  IO::Socket::INET6: 0
  Net::SSLeay: 0
  Net::Server: 2
  Net::Server::PreFork: 0
  Net::Server::Proto::SSLEAY: 0
  Net::Server::Single: 0
  Socket6: 0
version: 4
